version: 0.2

phases:
  install:
    commands:
      - echo $APP_NAME
      - echo $REACT_APP_ENV
      - echo $S3_BUCKET
      - echo $DISTRIBUTION_ID
  pre_build:
    commands:
      - git branch -r
      - git branch
      - git checkout feature/test-branch
      - npm install
  build:
    commands:
      - npm run build