version: 0.2

phases:
  install:
    commands:
      - echo $APP_NAME
      - echo $REACT_APP_ENV
      - echo $S3_BUCKET
      - echo $DISTRIBUTION_ID
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Creating .env"
      - aws ssm get-parameter --name "/$APP_NAME/$REACT_APP_ENV/envs" --with-decrypt | jq --raw-output ".Parameter.Value" > .env
      - npm run build
    finally:
      - rm -f .env*
  post_build:
    commands:
      - aws s3 sync --delete ./build $S3_BUCKET --acl public-read
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/service-worker.js $S3_BUCKET
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html $S3_BUCKET
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html /service-worker.js
artifacts:
  files:
    - '**/*'
  base-directory: build
